### ISSUE TITLE
ZkNewFromTitleSelection and ZkNewFromContentSelection only capture the first letter of range

### ISSUE THREAD

**Issue by amirography** [mickael-menu/zk-nvim#19]
Hey! 
So when I select a range of characters, and invoke `` '<,'>ZkNewFromTitleSelection`` or `` '<,'>ZkNewFromContentSelection``, the earlier makes a note with the title of the first letter of range and the later, a note with content of the first range. 
As an example 
this is a note:
```
# note one

this should become a link
```
When I enter visual mode and select ``this should become a link`` and invoke with the above commands I end up with the first note with this content:
```
# note one

[t](9a963a5c)his should become a link
```
and another note with this content:
```
# t
```

I have tried this with neovim versions
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld
```
and also the latest nightly build available on git. 
I have also disabled all my other configurations.
 
Here is the content of my ``.zk/config.toml``:
``` toml
# zk configuration file

[note]



filename = "{{id}}"

extension = "md"

template = "default.md"


id-charset = "hex"

id-length = 8

# Letter case for the random IDs, among lower, upper or mixed.
id-case = "lower"

[extra]

[group.journal]
paths = [
    "journal",
]
[group.journal.note]
filename = "{{date now}}"
[format.markdown]


hashtags = true
colon-tags = false
multiword-tags = false

[tool]
editor = "nvim"

pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[lsp]

[lsp.diagnostics]
dead-link = "error"

[lsp.completion]
note-label = "{{title-or-path}}"
note-filter-text = " {{title}} {{path}}"
note-detail = "{{filename-stem}}"

[filter]

[alias]
i = "zk edit -i"
ls = "zk list $@"
list = "zk list --quiet $@"
editlast = "zk edit --limit 1 --sort modified- $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
hist = "zk list --format path --delimiter0 --quiet $@ | xargs -t -0 git log --patch --"
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
```

Also here is the content of my ``zk.lua`` configuration file:
``` lua
require("zk").setup({
	picker = "select",
	lsp = {
		-- `config` is passed to `vim.lsp.start_client(config)`
		config = {
			cmd = { "zk", "lsp" },
			name = "zk",
			-- on_attach = ...
			-- etc, see `:h vim.lsp.start_client()`
		},
		-- automatically attach buffers in a zk notebook that match the given filetypes
		auto_attach = {
			enabled = true,
			filetypes = { "markdown" },
		},
	},
})
require("telescope").load_extension("zk")
vim.api.nvim_set_keymap("v", "N", ":ZkNewFromTitleSelection<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>zc", "<cmd>ZkNew<CR>", { noremap = true })
vim.api.nvim_set_keymap("x", "<Leader>zc", ":'<'>ZkNewFromTitleSelection<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>zn", "<cmd>ZkNotes<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>zb", "<cmd>ZkBacklinks<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>zl", "<cmd>ZkLinks<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>zt", "<cmd>ZkTags<CR>", { noremap = true })
```

Please tell me to provide any additional information, if needed.
